// scripts/build.js — produces dist/firefox/ and dist/chrome/ from source
// Usage: node scripts/build.js           (builds both)
//        node scripts/build.js firefox   (Firefox only)
//        node scripts/build.js chrome    (Chrome only)

const fs   = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const DIST = path.join(ROOT, "dist");
const POLY = path.join(ROOT, "node_modules", "webextension-polyfill", "dist", "browser-polyfill.js");

const COPY_ENTRIES = [
  "background.js",
  "content.js",
  "content.css",
  "lib",
  "popup",
  "options",
  "history",
  "icons",
];

// ── build-flags ────────────────────────────────────────────────────────────────

// Writes lib/build-flags.js into a built target directory.
// TEST_BUILD=true env var marks the build as a test-only build.
function writeBuildFlags(targetDir) {
  const testBuild = process.env.TEST_BUILD === 'true';
  fs.writeFileSync(
    path.join(targetDir, "lib", "build-flags.js"),
    `// auto-generated by scripts/build.js — do not edit\nconst BUILD_FLAGS = ${JSON.stringify({ testBuild })};\n`
  );
}

// Injects LICENSE_CIPHER_KEY into the built lib/license.js.
// The source file has the placeholder "%%LICENSE_CIPHER_KEY%%" — never the real value.
// Set the env var (or GitHub Actions secret) before building.
function injectLicenseKey(targetDir) {
  let key = process.env.LICENSE_CIPHER_KEY;

  // Fallback: read from C:\ETC\brainfix-ai.env on local dev machines
  if (!key) {
    const etcFile = path.join(__dirname, "..", "ETC", "brainfix-ai.env");
    if (fs.existsSync(etcFile)) {
      for (const line of fs.readFileSync(etcFile, "utf8").split("\n")) {
        const eq = line.indexOf("=");
        if (eq > 0 && line.slice(0, eq).trim() === "LICENSE_CIPHER_KEY") {
          key = line.slice(eq + 1).trim();
          break;
        }
      }
    }
  }

  if (!key) {
    console.error("ERROR: LICENSE_CIPHER_KEY is not set.");
    console.error("       Options:");
    console.error("       1. Pass inline:       LICENSE_CIPHER_KEY=... npm run build:chrome");
    console.error("       2. Add to .env file in project root");
    console.error("       3. Add to ETC\\brainfix-ai.env in project root");
    process.exit(1);
  }
  const licPath = path.join(targetDir, "lib", "license.js");
  const src     = fs.readFileSync(licPath, "utf8");
  if (!src.includes('"%%LICENSE_CIPHER_KEY%%"')) {
    console.error("ERROR: placeholder not found in lib/license.js — was it already patched?");
    process.exit(1);
  }
  fs.writeFileSync(licPath, src.replace('"%%LICENSE_CIPHER_KEY%%"', JSON.stringify(key)));
}

// ── helpers ────────────────────────────────────────────────────────────────────

function clean(dir) {
  if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true });
  fs.mkdirSync(dir, { recursive: true });
}

function copyRecursive(src, dest) {
  const stat = fs.statSync(src);
  if (stat.isDirectory()) {
    fs.mkdirSync(dest, { recursive: true });
    for (const entry of fs.readdirSync(src)) {
      copyRecursive(path.join(src, entry), path.join(dest, entry));
    }
  } else {
    if (src.endsWith(".svg")) return; // SVGs not allowed in extension packages
    fs.copyFileSync(src, dest);
  }
}

// ── build ──────────────────────────────────────────────────────────────────────

function buildTarget(name, manifestOverrides = {}, manifestRemovals = []) {
  const dir = path.join(DIST, name);
  clean(dir);

  for (const entry of COPY_ENTRIES) {
    copyRecursive(path.join(ROOT, entry), path.join(dir, entry));
  }

  if (!fs.existsSync(POLY)) {
    console.error("browser-polyfill.js not found — run: npm install");
    process.exit(1);
  }
  fs.copyFileSync(POLY, path.join(dir, "browser-polyfill.js"));

  const base     = JSON.parse(fs.readFileSync(path.join(ROOT, "manifest.json"), "utf8"));
  const manifest = { ...base, ...manifestOverrides };
  for (const key of manifestRemovals) delete manifest[key];
  fs.writeFileSync(path.join(dir, "manifest.json"), JSON.stringify(manifest, null, 2));

  console.log(`  built  dist/${name}/`);
}

// ── targets ────────────────────────────────────────────────────────────────────

const ALL_TARGETS = {
  firefox: () => {
    buildTarget("firefox", {
      browser_specific_settings: {
        gecko: {
          id: "brainfixai@bheck",
          data_collection_permissions: { required: ["none"], optional: [] }
        }
      },
      // Firefox MV2 uses "scripts" array instead of "service_worker"
      background: {
        scripts: [
          "browser-polyfill.js",
          "lib/build-flags.js",
          "lib/text.js",
          "lib/prompts.js",
          "lib/pricing.js",
          "lib/api.js",
          "lib/updater.js",
          "background.js"
        ]
      }
    });
    // Remove importScripts() — not available outside a service worker context
    const bgPath = path.join(DIST, "firefox", "background.js");
    const bg = fs.readFileSync(bgPath, "utf8")
      .replace(/^importScripts\([^)]*\);\n?/m, "");
    fs.writeFileSync(bgPath, bg);
    writeBuildFlags(path.join(DIST, "firefox"));
    injectLicenseKey(path.join(DIST, "firefox"));
  },
  chrome: () => {
    buildTarget("chrome", {}, ["browser_specific_settings"]);
    writeBuildFlags(path.join(DIST, "chrome"));
    injectLicenseKey(path.join(DIST, "chrome"));
  },
};

const requested = process.argv[2];
const targets   = requested ? [requested] : Object.keys(ALL_TARGETS);

for (const t of targets) {
  if (!ALL_TARGETS[t]) {
    console.error(`Unknown target "${t}". Choose: ${Object.keys(ALL_TARGETS).join(", ")}`);
    process.exit(1);
  }
  ALL_TARGETS[t]();
}

console.log("done.");
